services:
  redis:
    image: redis:6.2.6-alpine
    ports:
    - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: "rabbitmq"
    ports:
    - "5672:5672"
    - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
  
  hybrid-cache-api-instance-1:
    build:
      context: ../
      dockerfile: HybridCacheApi/Dockerfile
    environment:
    - "Redis__ConnectionString=redis:6379"
    - "RabbitMQ__HostName=rabbitmq"
    ports:
    - "42685:80"
    links:
    - "redis"
    - "rabbitmq"
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  hybrid-cache-api-instance-2:
    build:
      context: ../
      dockerfile: HybridCacheApi/Dockerfile
    environment:
    - "Redis__ConnectionString=redis:6379"
    - "RabbitMQ__HostName=rabbitmq"
    ports:
    - "42686:80"
    links:
    - "redis"
    - "rabbitmq"
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy