services:
  redis:
    image: redis:6.2.6-alpine
    ports:
    - "6379:6379"
  
  hybrid-cache-redis-api-instance-1:
    build:
      context: ../../
      dockerfile: Demos/HybridCacheApi.Redis/Dockerfile
    environment:
    - "Redis__ConnectionString=redis:6379"
    - UseResponseCompression=${USERESPONSECOMPRESSION:-false}
    ports:
    - "42685:80"
    links:
    - "redis"
    depends_on:
      redis:
        condition: service_started

  hybrid-cache-redis-api-instance-2:
    build:
      context: ../../
      dockerfile: Demos/HybridCacheApi.Redis/Dockerfile
    environment:
    - "Redis__ConnectionString=redis:6379"
    - UseResponseCompression=${USERESPONSECOMPRESSION:-false}
    ports:
    - "42686:80"
    links:
    - "redis"
    depends_on:
      redis:
        condition: service_started
