services:
  no-cache-api:
    build:
      context: ../../
      dockerfile: Demos/NoCacheApi/Dockerfile
    environment:
      - UseResponseCompression=${USERESPONSECOMPRESSION:-false}
    ports:
    - "42685:80"